# ============================================
# db/models/resume.py
# ============================================
# WHY THIS FILE EXISTS:
# Stores the parsed content of uploaded resumes.
#
# KEY DESIGN DECISION:
# We store the EXTRACTED TEXT, not the raw PDF.
# Why? Because every AI feature (matching, questions, cover letter)
# needs TEXT, not a binary PDF file.
#
# The original PDF → Azure Blob Storage (just for download)
# The extracted text → THIS table (for all AI operations)
# ============================================

from sqlalchemy import Column, String, Text, Integer, Boolean, ForeignKey, JSON
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import relationship
from db.base import BaseModel


class Resume(BaseModel):
    __tablename__ = "resumes"

    # ---- Foreign Key ----
    # ForeignKey = "this column must match an id in the users table"
    # If user is deleted → their resumes are deleted too (cascade set in User model)
    # index=True → fast lookup of "all resumes for user X"
    user_id = Column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    # ---- File Info ----
    original_filename = Column(String(255), nullable=False)  # "john_cv_2024.pdf"

    # URL in Azure Blob Storage where original PDF is saved
    # Null until we implement Blob Storage in deployment step
    blob_url = Column(String(500), nullable=True)

    # ---- Extracted Content ----
    # The full raw text extracted from PDF (what PyPDF gives us)
    raw_text = Column(Text, nullable=False)

    # ---- AI-Parsed Sections ----
    # JSON columns store structured data extracted by GPT.
    # PostgreSQL has native JSON support - you can query inside these.
    #
    # Example skills_extracted:
    # ["Python", "FastAPI", "PostgreSQL", "React", "Docker"]
    skills_extracted = Column(JSON, nullable=True, default=list)

    # Example experience_extracted:
    # [{"company": "Google", "role": "SWE", "years": 2, "description": "..."}]
    experience_extracted = Column(JSON, nullable=True, default=list)

    # Example education_extracted:
    # [{"degree": "B.Tech CS", "university": "IIT", "year": 2022}]
    education_extracted = Column(JSON, nullable=True, default=list)

    # Embedding vector for job matching similarity search
    # Stored as JSON array of 384 floats
    # Generated by HuggingFace all-MiniLM-L6-v2 (free, runs locally)    
    # Example: [0.023, -0.156, 0.891, ...]
    embedding = Column(JSON, nullable=True)

    # Normalized total experience extracted from GPT/parser.
    # These fields are used by resume APIs and job matching.
    experience_label = Column(String(100), nullable=True)
    experience_months = Column(Integer, nullable=True)

    # Is this the user's currently active resume?
    # Users can upload multiple resumes (different versions)
    is_active = Column(Boolean, default=True, nullable=False)

    # ---- Relationship ----
    user = relationship("User", back_populates="resumes")

    def __repr__(self):
        return f"<Resume {self.original_filename} for user {self.user_id}>"
